#!/usr/bin/env python3
"""One-time migration of the existing renderer to the two reviewed draft batches."""
from pathlib import Path
R=Path(__file__).resolve().parents[1]
p=R/'scripts/build_batch.py'
if "--batch" in p.read_text():raise SystemExit('Migration already applied; do not replay over later edits.')
p=R/'scripts/validate_project.py';s=p.read_text();s=s.replace("assert ''.join(e['character'] for e in batch['entries']) == batches['frozen_batches'][0]['main_glyphs']", "declared = next((b for b in batches['frozen_batches'] if b['id'] == batch['batch_id']), None)\n    assert declared is not None, 'Unknown batch ID'\n    assert ''.join(e['character'] for e in batch['entries']) == declared['main_glyphs']")
s=s.replace("'B01_primary_checked':len(batch['entries']),", "batch['batch_id']+'_primary_checked':len(batch['entries']),")
s=s.replace("'B01_cross_checked':10 if batch['cross_review']['status']=='passed' else 0,", "batch['batch_id']+'_cross_checked':len(batch['entries']) if batch['cross_review']['status']=='passed' else 0,")
s=s.replace("p.add_argument('--release', action='store_true')", "p.add_argument('--release', action='store_true')\n    p.add_argument('--batch', choices=['B01','B02'], default='B01')")
s=s.replace("'data/variants.json','data/B01.json']", "'data/variants.json',f'data/{args.batch}.json']");p.write_text(s)
p=R/'scripts/acquire_vectors.py';s=p.read_text().replace('import hashlib','import argparse\nimport hashlib');s=s.replace("entries=json.loads((ROOT/'data/B01.json').read_text(encoding='utf-8'))['entries']", "p=argparse.ArgumentParser();p.add_argument('--batches',nargs='+',choices=['B01','B02'],default=['B01']);args=p.parse_args()\n    entries=[]\n    for bid in args.batches: entries.extend(json.loads((ROOT/f'data/{bid}.json').read_text(encoding='utf-8'))['entries'])");p.write_text(s)
p=R/'scripts/build_batch.py';s=p.read_text();s=s.replace('def make_page(c,e,data,page_number,draft):','def make_page(c,e,data,page_number,draft,batch):');s=s.replace("'B01 / A4 / 田字格'", "batch['batch_id']+' / A4 / 田字格'");s=s.replace("label='编写稿｜规范笔顺图已核；第二权威来源、细笔名及拼音仍待交叉复核。' if draft else '已通过本工程发布门槛。'", "label=batch['draft_label'] if draft else '已通过本工程发布门槛。'");s=s.replace("f'B01 / {page_number:02}'", 'f"{batch[\'batch_id\']} / {page_number:02}"');s=s.replace('编写中 v0.1｜','编写中 v0.2｜');s=s.replace("p=argparse.ArgumentParser(); p.add_argument('--draft',action='store_true')", "p=argparse.ArgumentParser(); p.add_argument('--draft',action='store_true')\n    p.add_argument('--batch',choices=['B01','B02'],default='B01')");s=s.replace("'data/variants.json','data/B01.json']", "'data/variants.json',f'data/{args.batch}.json']");s=s.replace("pdf=out/f'B01_{mode}_A4.pdf'", "pdf=out/f'{args.batch}_{mode}_A4.pdf'");s=s.replace("c.setTitle('B01首批10项笔顺练字帖'", "c.setTitle(args.batch+'笔顺练字帖'");s=s.replace('make_page(c,e,d,i,args.draft)','make_page(c,e,d,i,args.draft,batch)');s=s.replace("pre=out/'preface_v0.1.pdf'", "pre=out/'preface_v0.2.pdf'");s=s.replace("combined=out/f'B01_with_preface_{mode}_A4.pdf'", "combined=out/f'{args.batch}_with_preface_{mode}_A4.pdf'");s=s.replace("(out/'generation.json')", "(out/f'generation_{args.batch}.json')");p.write_text(s)
p=R/'scripts/verify_pdf.py';s=p.read_text().replace('import json','import argparse\nimport json');s=s.replace("batch=json.loads((ROOT/'data/B01.json').read_text(encoding='utf-8'))", "parser=argparse.ArgumentParser();parser.add_argument('--batch',choices=['B01','B02'],default='B01');args=parser.parse_args()\nbatch=json.loads((ROOT/f'data/{args.batch}.json').read_text(encoding='utf-8'))");s=s.replace("ROOT/'build/B01_draft_A4.pdf'", "ROOT/f'build/{args.batch}_draft_A4.pdf'");s=s.replace("assert '编写稿' in txt and '第二权威来源' in txt", "assert '编写稿' in txt and batch['draft_label'] in txt");p.write_text(s)
p=R/'book/front-matter/preface.md';s=p.read_text().replace('编写中 v0.1','编写中 v0.2');s=s.replace('同一规范被不同网站转载，也不能算作多份独立证据。', '同一规范被不同网站转载，也不能算作多份独立证据。不同年份的规范虽然是不同出版物，仍可能有继承关系；本书注明这一点，不把版本对照说成独立专家审定。');s=s.replace('每份交付稿均标明版本；', '阶段性和最终PDF均按版本直接保存在工程仓库，旧稿保留，新稿另存，不以临时构建附件代替归档。每份交付稿均标明版本；');s=s.replace('- [S03] 《现代常用字部件及部件名称规范》GF0014—2009；名称条目仍需逐项核对。','- [S03] 《现代常用字部件及部件名称规范》GF0014—2009；已取得正式文本，按所用字段核对。\n- [S04—S07] 语文出版社1997年版笔顺规范、GF2001—2001折笔规范、GF0015—2010词汇读音表、GF0013—2009独体字规范。分别用于笔顺、笔名、读音和结构核对，不互相冒充支持范围。')
old='本次编写稿先呈现第一批10项：一、十、人、八、大、工、土、口、山、巾。学习顺序从单笔与横竖相交，过渡到撇捺配合，再比较工与土、山与巾的差异。10项的国家规范逐笔图已核看，矢量顺序和初稿版面已检查；第二权威来源及相关细笔名、拼音交叉核对尚未完成，因此本稿不作为终审版。'
new='本轮分两批呈现20个主项。第一批是一、十、人、八、大、工、土、口、山、巾，已逐项核对两部规范的笔顺图，并补齐所用笔名、结构和读音依据。第二批是水、火、木、日、月、田、目、手、牛、毛，已完成两部规范的笔顺图对照，读音等字段仍待补齐。两批按各自复核状态标识，不能把第一批的结论自动套给第二批。'
if old not in s:raise ValueError('Unexpected preface baseline')
p.write_text(s.replace(old,new))
