'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const Brush=require('../ink-brush.js');
const Gallery=require('../gallery.js');
const T=require('../timeline.js');
global.window=global;
require('../samples.js');
const glyphs=global.ZITIE_SAMPLES.glyphs;
delete global.window;
const find=c=>glyphs.find(g=>g.character===c);

test('gallery shows clickable canonical records and filters by batch, character and verified stroke name',()=>{
  assert.equal(glyphs.length,9);
  assert.deepEqual(Gallery.batches(glyphs),['B01','B02','B21']);
  assert.deepEqual(Gallery.filteredGlyphs(glyphs,'水').map(x=>x.character),['水']);
  assert.deepEqual(Gallery.filteredGlyphs(glyphs,'B02').map(x=>x.character),['火','水','月']);
  assert.deepEqual(Gallery.filteredGlyphs(glyphs,'横折','B01').map(x=>x.character),['口','巾']);
  assert.deepEqual(Gallery.filteredGlyphs(glyphs,'','B21').map(x=>x.character),['龠']);
  assert.equal(Gallery.filteredGlyphs(glyphs,'不存在').length,0);
  assert.equal(Gallery.neighbor(glyphs,201,1).character,'一');
  assert.equal(Gallery.neighbor(glyphs,1,-1).character,'龠');
});

test('samples follow every vendor median segment without inventing corner smoothing',()=>{
  const median=find('水').strokes[0].median;
  const samples=Brush.sampleMedian(median,13);
  assert.deepEqual([samples[0].x,samples[0].y],median[0]);
  assert.deepEqual([samples.at(-1).x,samples.at(-1).y],median.at(-1));
  assert.ok(samples.length>median.length);
  assert.ok(samples.every((p,i)=>i===0||p.distance>samples[i-1].distance));
  const length=T.polylineLength(median);
  assert.ok(Math.abs(samples.at(-1).distance-length)<0.001);
  for(const point of median){
    assert.ok(samples.some(p=>Math.abs(p.x-point[0])<0.001 && Math.abs(p.y-point[1])<0.001));
  }
});

test('contour probing estimates cross-sections on both sides without a hard-coded global width',()=>{
  const contains=(x,y)=>x>=0&&x<=200&&y>=-17&&y<=17;
  const profile=Brush.makeProfile([[4,0],[196,0]],contains,{spacing:12,margin:4});
  assert.equal(profile.method,'outline-cross-section');
  assert.ok(profile.sampledWithFill>8);
  assert.ok(profile.stations.every(s=>s.left>18&&s.left<23&&s.right>18&&s.right<23));
  assert.equal(Brush.revealPath(profile,0),'');
  assert.ok(Brush.revealPath(profile,0.25).includes(' Z'));
  assert.ok(Brush.revealPath(profile,1).length>Brush.revealPath(profile,0.5).length);
  assert.ok(Brush.revealPath(profile,0.02).length<Brush.revealPath(profile,0.5).length);
});

test('moving front never crosses later centerline stations on a straight stroke',()=>{
  const profile=Brush.makeProfile([[0,0],[100,0]],(x,y)=>x>=0&&x<=100&&Math.abs(y)<15);
  for(const progress of [0.05,0.25,0.5,0.75,0.95]){
    const d=Brush.revealPath(profile,progress);
    const nums=(d.match(/-?\d+(?:\.\d+)?/g)||[]).map(Number);
    // x values at even-numbered tokens; normals for horizontal travel have nx=0.
    const xs=nums.filter((_,i)=>i%2===0);
    assert.ok(xs.length>0);
    assert.ok(Math.max(...xs)<=100*progress+0.05, 'ink advanced past current pen tip at '+progress);
    assert.ok(Math.min(...xs)>=-0.05);
  }
});

test('fallback width flags unknown fill probing, rather than rewriting median points',()=>{
  const original=find('龠').strokes[13].median;
  const before=JSON.stringify(original);
  const fallback=Brush.makeProfile(original,null,{fallbackRadius:50});
  assert.equal(fallback.method,'fallback-no-fill-API');
  assert.equal(fallback.sampledWithFill,0);
  assert.ok(fallback.stations.every(s=>s.left===50&&s.right===50));
  assert.equal(JSON.stringify(original),before);
});

test('no NaN paths, and no extra stroke generated by hooks or folds',()=>{
  for(const g of glyphs){
    assert.equal(T.validateGlyph(g),true);
    for(const s of g.strokes){
      const p=Brush.makeProfile(s.median,null);
      for(const n of [0,0.02,0.1,0.5,0.95,1]){
        const d=Brush.revealPath(p,n);
        assert.ok(!d.includes('NaN')&&!d.includes('Infinity'));
        if(n===0)assert.equal(d,'');
        else assert.ok(d.startsWith('M '));
      }
    }
  }
});
